(deftheme Arc-Dark
  "Created 2017-02-21.")

(custom-theme-set-variables
 'Arc-Dark
 '(ansi-color-names-vector ["#2F343F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"])
 '(fci-rule-color "#383838"))

(custom-theme-set-faces
 'Arc-Dark
 '(default ((t (:foreground "#d1d1d1" :background "#2F343F"))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#ffffff"))))
 '(highlight ((t (:background "#383838"))))
 '(region ((((class color) (min-colors 89)) (:background "#5294E2")) (t :inverse-video t)))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#29303A"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#2F343F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#29303A"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#2F343F"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(anzu-mode-line ((t (:foreground "#93E0E3" :weight bold))))
 '(anzu-mode-line-no-match ((t (:foreground "#CC9393" :weight bold))))
 '(anzu-match-1 ((t (:foreground "#2F343F" :background "#7F9F7F"))))
 '(anzu-match-2 ((t (:foreground "#2F343F" :background "#DFAF8F"))))
 '(anzu-match-3 ((t (:foreground "#2F343F" :background "#8CD0D3"))))
 '(anzu-replace-to ((t (:inherit anzu-replace-highlight :foreground "#F0DFAF"))))
 '(popup-tip-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-menu-mouse-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-summary-face ((t (:background "#6F6F6F" :foreground "#000000"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2B2B2B"))))
 '(popup-isearch-match ((t (:background "#2F343F" :foreground "#DCDCCC"))))
 '(company-tooltip ((t (:foreground "#DCDCCC" :background "#29303A"))))
 '(company-tooltip-annotation ((t (:foreground "#DFAF8F" :background "#29303A"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#DFAF8F" :background "#5294E2"))))
 '(company-tooltip-selection ((t (:foreground "#DCDCCC" :background "#5294E2"))))
 '(company-tooltip-mouse ((t (:background "#2B2B2B"))))
 '(company-tooltip-common ((t (:foreground "#9FC59F"))))
 '(company-tooltip-common-selection ((t (:foreground "#9FC59F"))))
 '(company-scrollbar-fg ((t (:background "#2B2B2B"))))
 '(company-scrollbar-bg ((t (:background "#5F5F5F"))))
 '(company-preview ((t (:background "#9FC59F"))))
 '(company-preview-common ((t (:foreground "#9FC59F" :background "#2B2B2B"))))
 '(diff-added ((t (:background "#335533" :foreground "#7F9F7F"))))
 '(diff-changed ((t (:background "#555511" :foreground "#E0CF9F"))))
 '(diff-removed ((t (:background "#553333" :foreground "#AC7373"))))
 '(diff-refine-added ((t (:background "#338833" :foreground "#BFEBBF"))))
 '(diff-refine-changed ((t (:background "#888811" :foreground "#F0DFAF"))))
 '(diff-refine-removed ((t (:background "#883333" :foreground "#CC9393"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5F5F5F")) (t (:background "#DCDCCC" :foreground "#2F343F"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5F5F5F" :foreground "#DCDCCC" :weight bold)) (t (:background "#DCDCCC" :foreground "#2F343F" :weight bold))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#8CD0D3" :background "#6CA0A3"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#DCA3A3" :background "#BC8383"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#5F7F5F"))))
 '(flx-highlight-face ((t (:foreground "#9FC59F" :weight bold))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#BC8383") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#F0DFAF") :inherit unspecified)) (t (:foreground "#F0DFAF" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave))) (:underline (:style wave :color "#93E0E3") :inherit unspecified)) (t (:foreground "#93E0E3" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#BC8383" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#F0DFAF" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "#93E0E3" :weight bold))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(git-commit-comment-action ((((class color) (min-colors 89)) (:foreground "#8FB28F" :weight bold))))
 '(git-commit-comment-branch ((((class color) (min-colors 89)) (:foreground "#94BFF3" :weight bold))))
 '(git-commit-comment-heading ((((class color) (min-colors 89)) (:foreground "#F0DFAF" :weight bold))))
 '(git-gutter:added ((t (:foreground "#7F9F7F" :weight bold :inverse-video t))))
 '(git-gutter:deleted ((t (:foreground "#CC9393" :weight bold :inverse-video t))))
 '(git-gutter:modified ((t (:foreground "#DC8CC3" :weight bold :inverse-video t))))
 '(git-gutter:unchanged ((t (:foreground "#DCDCCC" :weight bold :inverse-video t))))
 '(helm-header ((t (:foreground "#7F9F7F" :background "#2F343F" :underline nil :box nil))))
 '(helm-source-header ((t (:foreground "#F0DFAF" :background "#2F343F" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((t (:background "#29303A" :underline nil))))
 '(helm-selection-line ((t (:background "#29303A"))))
 '(helm-visible-mark ((t (:foreground "#2F343F" :background "#D0BF8F"))))
 '(helm-candidate-number ((t (:foreground "#BFEBBF" :background "#2B2B2B"))))
 '(helm-separator ((t (:foreground "#CC9393" :background "#2F343F"))))
 '(helm-bookmark-addressbook ((t (:foreground "#DFAF8F" :background "#2F343F"))))
 '(helm-bookmark-directory ((t (:foreground nil :background nil :inherit helm-ff-directory))))
 '(helm-bookmark-file ((t (:foreground nil :background nil :inherit helm-ff-file))))
 '(helm-bookmark-gnus ((t (:foreground "#DC8CC3" :background "#2F343F"))))
 '(helm-bookmark-info ((t (:foreground "#9FC59F" :background "#2F343F"))))
 '(helm-bookmark-man ((t (:foreground "#F0DFAF" :background "#2F343F"))))
 '(helm-bookmark-w3m ((t (:foreground "#DC8CC3" :background "#2F343F"))))
 '(helm-buffer-not-saved ((t (:foreground "#CC9393" :background "#2F343F"))))
 '(helm-buffer-process ((t (:foreground "#93E0E3" :background "#2F343F"))))
 '(helm-buffer-saved-out ((t (:foreground "#DCDCCC" :background "#2F343F"))))
 '(helm-buffer-size ((t (:foreground "#656555" :background "#2F343F"))))
 '(helm-ff-directory ((t (:foreground "#93E0E3" :background "#2F343F" :weight bold))))
 '(helm-ff-file ((t (:foreground "#DCDCCC" :background "#2F343F" :weight normal))))
 '(helm-ff-executable ((t (:foreground "#9FC59F" :background "#2F343F" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#CC9393" :background "#2F343F" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "#F0DFAF" :background "#2F343F" :weight bold))))
 '(helm-ff-prefix ((t (:foreground "#2F343F" :background "#F0DFAF" :weight normal))))
 '(helm-grep-cmd-line ((t (:foreground "#93E0E3" :background "#2F343F"))))
 '(helm-grep-file ((t (:foreground "#DCDCCC" :background "#2F343F"))))
 '(helm-grep-finish ((t (:foreground "#9FC59F" :background "#2F343F"))))
 '(helm-grep-lineno ((t (:foreground "#656555" :background "#2F343F"))))
 '(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
 '(helm-match ((t (:foreground "#DFAF8F" :background "#2B2B2B" :weight bold))))
 '(helm-moccur-buffer ((t (:foreground "#93E0E3" :background "#2F343F"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#29303A")) (t :weight bold)))
 '(hydra-face-red ((t (:foreground "#BC8383" :background "#2F343F"))))
 '(hydra-face-amaranth ((t (:foreground "#9C6363" :background "#2F343F"))))
 '(hydra-face-blue ((t (:foreground "#8CD0D3" :background "#2F343F"))))
 '(hydra-face-pink ((t (:foreground "#DC8CC3" :background "#2F343F"))))
 '(hydra-face-teal ((t (:foreground "#93E0E3" :background "#2F343F"))))
 '(ido-first-match ((t (:foreground "#F0DFAF" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(ido-indicator ((t (:foreground "#F0DFAF" :background "#8C5353"))))
 '(linum ((t (:foreground "#9FC59F" :background "#29303A"))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-name ((t (:foreground "#8FB28F"))))
 '(message-header-other ((t (:foreground "#7F9F7F"))))
 '(message-header-to ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-cc ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-subject ((t (:foreground "#DFAF8F" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7F9F7F"))))
 '(message-mml ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment-face))))
 '(org-agenda-date-today ((t (:foreground "#FFFFEF" :slant italic :weight bold))))
 '(outline-1 ((t (:foreground "#DFAF8F"))))
 '(outline-2 ((t (:foreground "#BFEBBF"))))
 '(outline-3 ((t (:foreground "#7CB8BB"))))
 '(outline-4 ((t (:foreground "#D0BF8F"))))
 '(outline-5 ((t (:foreground "#93E0E3"))))
 '(outline-6 ((t (:foreground "#9FC59F"))))
 '(outline-7 ((t (:foreground "#8C5353"))))
 '(outline-8 ((t (:foreground "#4C7073"))))
 '(powerline-active1 ((t (:background "#383838" :inherit mode-line))))
 '(powerline-active2 ((t (:background "#29303A" :inherit mode-line))))
 '(powerline-inactive1 ((t (:background "#2B2B2B" :inherit mode-line-inactive))))
 '(powerline-inactive2 ((t (:background "#2f343f" :inherit mode-line-inactive))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#DCDCCC"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#BFEBBF"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#D0BF8F"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#93E0E3"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#9FC59F"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#94BFF3"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E0CF9F"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8FB28F"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6CA0A3"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:background "#6F6F6F" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#6F6F6F" :weight bold))))
 '(term-color-black ((t (:foreground "#2F343F" :background "#2B2B2B"))))
 '(term-color-red ((t (:foreground "#AC7373" :background "#8C5353"))))
 '(term-color-green ((t (:foreground "#7F9F7F" :background "#9FC59F"))))
 '(term-color-yellow ((t (:foreground "#DFAF8F" :background "#F0DFAF"))))
 '(term-color-blue ((t (:foreground "#7CB8BB" :background "#4C7073"))))
 '(term-color-magenta ((t (:foreground "#DC8CC3" :background "#CC9393"))))
 '(term-color-cyan ((t (:foreground "#93E0E3" :background "#8CD0D3"))))
 '(term-color-white ((t (:foreground "#DCDCCC" :background "#656555"))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#FFFFEF" :weight bold))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#BC8383" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#DCDCCC"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#F0DFAF"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#93E0E3"))))
 '(vhl/default-face ((t (:background "#383838")))))

(provide-theme 'Arc-Dark)
