(deftheme moe-dark
  "Created 2017-05-20.")

(custom-theme-set-variables
 'moe-dark
 '(ansi-color-names-vector ["#303030" "#ff4b4b" "#d7ff5f" "#fce94f" "#5fafd7" "#d18aff" "#afd7ff" "#c6c6c6"]))

(custom-theme-set-faces
 'moe-dark
 '(cursor ((((class color) (min-colors 89)) (:background "#c6c6c6"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#a8a8a8" :background "#4e4e4e"))))
 '(linum ((t (:background "#4e4e4e" :foreground "#b2b2b2"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(region ((t (:background "#d7ff5f" :foreground "#4e4e4e"))))
 '(secondary-selection ((t (:background "#005f87" :foreground "#ffffff"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff5d17"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#ff1f8b" :foreground "#c6c6c6"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#a40000"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#005f87" :foreground nil))))
 '(header-line ((t (:background "#005f87" :foreground "#ffffff"))))
 '(help-argument-name ((((class color) (min-colors 89)) (:foreground "#ff7bbb" :italic t))))
 '(mode-line ((t (:background "#afd7ff" :foreground "blue violet" :box nil))))
 '(mode-line-inactive ((t (:background "#6c6c6c" :foreground "#c6c6c6" :box nil))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:box nil :foreground "#303030" :background nil :bold t))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#4e4e4e"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#a1db00"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(warning ((t (:foreground "#ffaf5f"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#6c6c6c" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#fce94f"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#dd0000"))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:weight bold :foreground "#ff8700"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#303030" :weight bold))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :weight bold))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#ffaf5f" :background "#6c6c6c"))))
 '(org-archived ((((class color) (min-colors 89)) (:slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#c6c6c6" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#afd7ff" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#008700" :background "#d7ff5f" :box (:line-width 1 :style none)))))
 '(org-todo ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#a40000" :background "#ffaf87" :box (:line-width 1 :style none)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(org-tag ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6" :bold t :weight bold))))
 '(org-column ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#4e4e4e"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#afd7ff" :foreground "#303030" :underline t :weight bold))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#00ac8a" :background nil :bold t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6"))))
 '(org-table ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#c6c6c6"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-warning ((((class color) (min-colors 89)) (:bold t :foreground "#ffffff" :background "#a40000"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#303030"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#3a3a3a"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :underline nil))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline nil :bold nil))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#6c6c6c" :slant italic :weight bold))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#4e4e4e" :underline t))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#a1db00" :background nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#dd0000"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#ef2929" :background nil))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#3a3a3a"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#005f87"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#3a3a3a"))))
 '(org-quote ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ef2929" :bold t))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e" :bold nil))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(outline-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(outline-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(outline-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#ff4ea3" :bold t))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#3a3a3a"))))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#afd7ff"))))
 '(popup-menu-summary-face ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#4e4e4e"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#8a8a8a" :foreground "#b2b2b2"))))
 '(popup-summary-face ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#6c6c6c" :foreground "#c6c6c6"))))
 '(company-echo ((((class color) (min-colors 89)) (:background nil :foreground "#c6c6c6"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#ef2929"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#303030" :foreground "#ff4ea3"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#303030" :foreground "#ff4ea3"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#ff4ea3" :bold t))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#b2b2b2"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#ffffaf" :foreground "#3a3a3a"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#5fafd7"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#ef2929"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#6c6c6c" :foreground "#afd7ff"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#afd7ff" :bold t))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#303030"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#afd7ff"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#5fafd7"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#1f5bff"))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :bold t))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffff87"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#dd0000" :background "#303030"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#ffffff"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#303030" :bold t))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#303030"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#dd0000"))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff8700"))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :bold t))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#fce94f" :bold t))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#d7ff5f"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "#a1db00" :background "#303030" :bold t))))
 '(helm-selection ((((class color) (min-colors 89)) (:foreground nil :background "#005f87"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:foreground nil :background "#875f00"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#6c6c6c" :bold t))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :background "#ffafd7"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#303030" :background "#a1db00" :bold t))))
 '(dired-ignored ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#dd0000" :bold t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#a40000" :bold t))))
 '(magit-bisect-bad ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf"))))
 '(magit-bisect-good ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f"))))
 '(magit-bisect-skip ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffd787"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(magit-blame-hash ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#4e4e4e"))))
 '(magit-blame-name ((((class color) (min-colors 89)) (:foreground "#afff00" :background "#4e4e4e"))))
 '(magit-blame-summary ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#4e4e4e"))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ff8700" :bold t :underline nil))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :bold t :underline t))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t :underline t))))
 '(magit-cherry-equivalent ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(magit-cherry-unmatched ((t (:foreground "#00ac8a"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background nil :bold t))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :bold t :inherit (magit-section-highlight)))))
 '(magit-diff-base ((((class color) (min-colors 89)) (:foreground "#fce94f" :background nil))))
 '(magit-diff-base-highlight ((((class color) (min-colors 89)) (:foreground "#fce94f" :bold t :inherit (magit-section-highlight)))))
 '(magit-diff-conflict-heading ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ff8700"))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background nil))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :inherit (magit-section-highlight)))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:foreground "#ffffff" :bold t))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 89)) (:background "#005f87" :bold t))))
 '(magit-diff-file-heading-selection ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#8a8a8a" :bold t))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background "#4e4e4e" :bold t))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#c3c9f8"))))
 '(magit-diff-hunk-heading-selection ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#c6c6c6"))))
 '(magit-diff-lines-boundary ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff4b4b"))))
 '(magit-diff-lines-heading ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff4b4b"))))
 '(magit-diff-our ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(magit-diff-our-highlight ((((class color) (min-colors 89)) (:foreground "#ff1f8b" :background "#ffd7ff"))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background nil :bold t))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :bold t :inherit (magit-section-highlight)))))
 '(magit-diff-their ((((class color) (min-colors 89)) (:foreground "#00ac8a"))))
 '(magit-diff-their-highlight ((((class color) (min-colors 89)) (:foreground "#005f5f" :background "#87ffff"))))
 '(magit-diff-whitespace-warning ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#a40000"))))
 '(magit-diffstat-added ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff5f" :bold t))))
 '(magit-diffstat-removed ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ff4b4b" :bold t))))
 '(magit-dimmed ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(magit-filename ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#ff8700" :background nil))))
 '(magit-head ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd7af"))))
 '(magit-header-line ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#a1db00" :background nil))))
 '(magit-log-date ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background nil))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background nil))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :underline t))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff87" :underline t))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#ff1f8b" :background "#ffd7ff"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff87"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd787"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffff87"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#6c0099" :background "#e6a8df"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#4e4e4e"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#005f5f" :background "#87d7af"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#005faf" :background "#afd7ff"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#ff5d17" :background nil :bold t :underline t))))
 '(magit-section-heading-selection ((((class color) (min-colors 89)) (:background "#afd7ff"))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(magit-sequence-done ((((class color) (min-colors 89)) (:foreground "#5faf00"))))
 '(magit-sequence-drop ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(magit-sequence-head ((((class color) (min-colors 89)) (:foreground "#1f5bff"))))
 '(magit-sequence-onto ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(magit-sequence-part ((((class color) (min-colors 89)) (:foreground "#00ac8a"))))
 '(magit-sequence-pick ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(magit-sequence-stop ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(magit-signature-bad ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(magit-signature-good ((((class color) (min-colors 89)) (:foreground "#5faf00"))))
 '(magit-signature-untrusted ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#3a3a3a"))))
 '(magit-log-date ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#3a3a3a"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#3a3a3a"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :underline t :bold t))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :underline t :bold t))))
 '(magit-signature-bad ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(magit-signature-good ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(magit-signature-untrusted ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#afd7ff"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#ff7bbb"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#ffffff" :bold t))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t :bold t))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#3a3a3a" :bold t))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#ffd700" :background "#3a3a3a" :bold t))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#303030" :background "#afd7ff" :bold t))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#c6c6c6"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#4e4e4e" :bold t))))
 '(diff-index ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#b2b2b2" :bold t))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#5faf00" :bold t))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#c4a000" :bold t))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#a40000" :bold t))))
 '(diff-nonexistent ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#a40000" :bold t))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#008700" :bold t))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#875f00" :bold t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#a40000" :bold t))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background "#3a3a3a" :bold t))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#ffffff"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline t foreground-color "#ffaf5f"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:background "#ef2929" :foreground "#c6c6c6" :bold t))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:bold t :foreground "#dd0000"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:bold t :foreground "#5fafd7"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:bold t :foreground "#a1db00"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:bold t :foreground "#ff4ea3"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:bold t :foreground "#00d7af"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:bold t :foreground "#ff8700"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:bold t :foreground "#af5fff"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:bold t :foreground "#c6c6c6"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:bold t :foreground "#ffd700"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#a40000" :bold t))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#6c6c6c" :bold t))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline "#ff8700"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline "#dd0000"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:background "#dd0000" :foreground "#ffffff" :bold t))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t))))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :bold t))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffd787"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#a1db00" :background nil))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(vhl/default-face ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#d7ff5f"))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f" :bold t))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :bold t))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffff87" :bold t))))
 '(widget-button ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t :bold t))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#afd7ff"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(widget-field ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#4e4e4e"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#4e4e4e"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ff4b4b" :bold t))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f" :bold t))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :bold t))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd787" :bold t))))
 '(compilation-warning ((((class color) (min-colors 89)) (:foreground "#ff5d17"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background nil :bold t))))
 '(info-index-match ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#ffffff" :bold t :underline t))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(info-title-3 ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t))))
 '(info-title-4 ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline t))))
 '(haskell-interactive-face-compile-error ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background nil :bold t))))
 '(haskell-interactive-face-compile-warning ((((class color) (min-colors 89)) (:foreground "#ff8700" :background nil :bold t))))
 '(haskell-interactive-face-garbage ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(haskell-interactive-face-prompt ((((class color) (min-colors 89)) (:foreground "#d7ff00" :background "#6c6c6c" :bold t))))
 '(haskell-interactive-face-result ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#a8a8a8" :background "#4e4e4e"))))
 '(tty-menu-disabled-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :background "#4e4e4e"))))
 '(tty-menu-enabled-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#4e4e4e" :bold t))))
 '(tty-menu-selected-face ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#afd7ff" :foreground "#005f87" :box (:line-width 1 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#d7d7ff" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#c6c6c6" :box (:line-width 1 :style pressed-button)))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(hydra-face-amaranth ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(default ((((class color) (min-colors 4096)) (:foreground "#c6c6c6" :background "#303030")) (((class color) (min-colors 256)) (:foreground "#c6c6c6" :background "#303030")) (((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#303030")))))

(provide-theme 'moe-dark)
